using System.Collections.Generic;
using Shadowbound.Core.Combat;
using Shadowbound.Core.Content;
using Shadowbound.Core.Numerics;
using Shadowbound.Core.Progression;
using Shadowbound.Core.Randomness;
using Shadowbound.Core.Serialization;
using Shadowbound.Core.Simulation;
using Shadowbound.Game.Combat;
using Shadowbound.Game.Player;
using Shadowbound.Game.Save;
using Shadowbound.Game.Ui;
using UnityEngine;

namespace Shadowbound.Game
{
    /// <summary>
    /// The entry point. Drop this on an empty GameObject in a scene and press Play.
    ///
    /// Everything the game needs is created here: content, session, player, arena,
    /// enemies, camera and HUD. The scene therefore contains almost nothing, which
    /// is deliberate - there are no hand-authored prefabs or binary scene files to
    /// drift out of step with the code, and the same bootstrap works on a scene
    /// generated by the editor tooling and on a bare one.
    ///
    /// Visuals are built from primitives at runtime so the game is playable
    /// immediately. Real art replaces the shapes registered in
    /// <see cref="CreateView"/>; nothing else needs to change.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class GameBootstrap : MonoBehaviour
    {
        [Header("Arena")]
        public float ArenaHalfExtent = 38f;

        public int Seed = 20250925;

        [Header("Content")]
        public bool BuildArenaGeometry = true;
        public bool SpawnEnemies = true;
        public bool BuildHud = true;

        [Header("Save")]
        public string SaveSlot = "slot-1";
        public bool LoadSaveOnStart;
        public bool AutoSave = true;
        public float AutoSaveIntervalSeconds = 60f;

        /// <summary>Placement of the opening encounter: creature, X, Z, level.</summary>
        private struct SpawnPlanEntry
        {
            public string Archetype;
            public float X;
            public float Z;
            public int Level;
        }

        private static readonly SpawnPlanEntry[] SpawnPlan =
        {
            // Close, easy, and in view from the start so the first fight happens
            // without the player having to go looking for it.
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeHollowWalker, X = 8f, Z = 12f, Level = 1 },
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeHollowWalker, X = -9f, Z = 14f, Level = 1 },
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeHollowWalker, X = 0f, Z = 18f, Level = 2 },

            // Mid field. Cinder Hounds are fast and set things on fire.
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeCinderHound, X = 14f, Z = -6f, Level = 3 },
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeCinderHound, X = -14f, Z = -8f, Level = 3 },

            // The elites, guarding the far end.
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeVeilwarden, X = 10f, Z = -24f, Level = 6 },
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeVeilwarden, X = -10f, Z = -24f, Level = 6 },

            // The chapter boss.
            new SpawnPlanEntry { Archetype = GameContent.ArchetypeAshenSentinel, X = 0f, Z = -33f, Level = 10 }
        };

        public GameSession Session { get; private set; }

        public PlayerInputDriver InputDriver { get; private set; }

        public ThirdPersonCamera CameraRig { get; private set; }

        public HudController Hud { get; private set; }

        public SaveSlotManager SaveManager { get; private set; }

        /// <summary>Every spawned view, so the frame loop can sync them without allocating.</summary>
        private readonly List<CombatantView> _views = new List<CombatantView>(16);

        private readonly Dictionary<string, CombatantView> _viewsById = new Dictionary<string, CombatantView>();

        private float _autoSaveTimer;
        private bool _started;

        private void Awake()
        {
            Build();
        }

        private void OnDestroy()
        {
            if (Hud != null)
            {
                Hud.Dispose();
            }
        }

        /// <summary>Builds a complete playable session. Safe to call again to restart.</summary>
        public void Build()
        {
            _started = true;

            BuildSession();
            BuildArena();
            BuildPlayer();
            BuildEnemies();
            BuildHud();

            if (LoadSaveOnStart)
            {
                TryLoad();
            }
        }

        private void BuildSession()
        {
            var items = GameContent.BuildItems();
            Combatant player = GameContent.CreatePlayer();

            Session = new GameSession(
                player,
                items,
                new ExperienceCurve(),
                GameContent.BuildPlayerGrowth(),
                new DeterministicRng((ulong)Seed),
                WorldBounds.Square(ArenaHalfExtent));

            GameContent.Populate(Session);

            SaveManager = new SaveSlotManager(
                new FileSaveStorage(),
                () => System.DateTimeOffset.UtcNow.ToUnixTimeSeconds());

            // The opening quest is offered immediately, so there is always
            // something to do the moment the game starts.
            Session.Quests.TryStart(GameContent.QuestArrival);
        }

        private void BuildPlayer()
        {
            InputDriver = new PlayerInputDriver();

            Session.Encounter.AddDriven(
                Session.Player,
                GameContent.BuildPlayerAbilities(),
                InputDriver,
                isPlayer: true);

            CombatantView view = CreateView(
                Session.Player,
                new Color(0.86f, 0.78f, 0.62f),
                1.05f,
                PrimitiveType.Capsule);

            GameObject cameraObject = new GameObject("Game Camera");
            cameraObject.transform.SetParent(transform, false);

            Camera camera = cameraObject.AddComponent<Camera>();
            camera.fieldOfView = 55f;
            camera.nearClipPlane = 0.15f;
            camera.farClipPlane = 400f;
            cameraObject.AddComponent<AudioListener>();
            cameraObject.tag = "MainCamera";

            CameraRig = cameraObject.AddComponent<ThirdPersonCamera>();
            CameraRig.Camera = camera;
            CameraRig.Driver = InputDriver;
            CameraRig.SetTarget(view.transform, Session.Player);
            CameraRig.Distance = 6.5f;

            // The Warden gets on-screen controls on a touch device, and keyboard
            // and mouse otherwise. Both feed the same driver.
            InputDriver.DeviceInputEnabled = !Application.isMobilePlatform;
        }

        private void BuildEnemies()
        {
            if (!SpawnEnemies)
            {
                return;
            }

            for (int i = 0; i < SpawnPlan.Length; i++)
            {
                SpawnPlanEntry entry = SpawnPlan[i];

                EnemyArchetype archetype = GameContent.FindArchetype(entry.Archetype);
                if (archetype == null)
                {
                    Debug.LogWarning("Spawn plan names unknown archetype '" + entry.Archetype + "'.");
                    continue;
                }

                var position = new Float3(entry.X, 0f, entry.Z);
                Combatant combatant = archetype.Create(entry.Archetype + "-" + i, position, entry.Level);

                Session.Encounter.AddEnemy(
                    combatant,
                    archetype.Abilities,
                    archetype.Brain,
                    archetype.AttackAbilityIndex);

                CreateView(
                    combatant,
                    ResolveTint(archetype),
                    archetype.BodyScale,
                    archetype.IsBoss ? PrimitiveType.Cube : PrimitiveType.Capsule);
            }
        }

        /// <summary>Creates a primitive body, a view, and wires the two together.</summary>
        public CombatantView CreateView(Combatant combatant, Color tint, float scale, PrimitiveType shape)
        {
            GameObject body = GameObject.CreatePrimitive(shape);
            body.name = "View " + combatant.Id;

            // Primitive colliders are not used: the core owns every position, so a
            // physics response would be a second, conflicting authority.
            Collider collider = body.GetComponent<Collider>();
            if (collider != null)
            {
                Destroy(collider);
            }

            Renderer renderer = body.GetComponent<Renderer>();
            if (renderer != null)
            {
                renderer.sharedMaterial = CreateMaterial(tint);
                renderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.On;
            }

            body.transform.SetParent(transform, false);
            body.transform.localScale = Vector3.one * scale;

            float height = shape == PrimitiveType.Capsule ? 1f : 0.5f;

            CombatantView view = body.AddComponent<CombatantView>();
            view.VerticalOffset = height * scale;
            view.Bind(combatant, renderer, scale);

            // A boss gets a heavy camera shake on every hit, which is the cheapest
            // way to make a large enemy feel like one.
            if (combatant.IsBoss)
            {
                view.Hit += _ => CameraRig?.Shake(0.5f);
            }
            else
            {
                view.Hit += _ => CameraRig?.Shake(0.12f);
            }

            view.Died += () => OnViewDied(view);

            _views.Add(view);
            _viewsById[combatant.Id] = view;

            return view;
        }

        private void OnViewDied(CombatantView view)
        {
            if (view.Combatant == null || view.Combatant.IsBoss)
            {
                return;
            }

            // Corpses stay for a moment so a kill is not invisible, then are
            // removed. Rewards were already granted by the session.
            _deadViews.Add(view);
            _deadViewTimers.Add(1.6f);
        }

        private readonly List<CombatantView> _deadViews = new List<CombatantView>();
        private readonly List<float> _deadViewTimers = new List<float>();

        /// <summary>
        /// Reads an archetype's placeholder colour. Authored data can be short or
        /// absent, and a malformed array should give a drab creature rather than
        /// an exception during spawn.
        /// </summary>
        private static Color ResolveTint(EnemyArchetype archetype)
        {
            float[] rgb = archetype.TintRgb;

            if (rgb == null || rgb.Length < 3)
            {
                return new Color(0.5f, 0.5f, 0.5f);
            }

            return new Color(rgb[0], rgb[1], rgb[2]);
        }

        private void BuildArena()
        {
            if (!BuildArenaGeometry)
            {
                return;
            }

            GameObject arena = new GameObject("Arena");
            arena.transform.SetParent(transform, false);

            // Ground.
            GameObject ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
            ground.name = "Ground";
            ground.transform.SetParent(arena.transform, false);
            ground.transform.localScale = Vector3.one * (ArenaHalfExtent * 0.2f);
            ApplyMaterial(ground, new Color(0.13f, 0.13f, 0.15f));

            // Walls, so the player cannot walk out of the arena.
            float wallHeight = 4f;
            float span = ArenaHalfExtent;

            CreateBlock(arena.transform, "Wall North", new Vector3(0f, wallHeight * 0.5f, span), new Vector3(span * 2f, wallHeight, 1f));
            CreateBlock(arena.transform, "Wall South", new Vector3(0f, wallHeight * 0.5f, -span), new Vector3(span * 2f, wallHeight, 1f));
            CreateBlock(arena.transform, "Wall East", new Vector3(span, wallHeight * 0.5f, 0f), new Vector3(1f, wallHeight, span * 2f));
            CreateBlock(arena.transform, "Wall West", new Vector3(-span, wallHeight * 0.5f, 0f), new Vector3(1f, wallHeight, span * 2f));

            // Scattered pillars give the enemies something to break line of sight
            // against, which is what makes their vision cone matter.
            CreateBlock(arena.transform, "Pillar 1", new Vector3(6f, 1.5f, 4f), new Vector3(1.6f, 3f, 1.6f));
            CreateBlock(arena.transform, "Pillar 2", new Vector3(-7f, 1.5f, 2f), new Vector3(1.6f, 3f, 1.6f));
            CreateBlock(arena.transform, "Pillar 3", new Vector3(3f, 1.5f, -12f), new Vector3(2.2f, 3f, 2.2f));
            CreateBlock(arena.transform, "Pillar 4", new Vector3(-4f, 1.5f, -14f), new Vector3(2.2f, 3f, 2.2f));

            if (FindLight() == null)
            {
                GameObject lightObject = new GameObject("Key Light");
                lightObject.transform.SetParent(arena.transform, false);
                lightObject.transform.rotation = Quaternion.Euler(48f, 145f, 0f);

                Light light = lightObject.AddComponent<Light>();
                light.type = LightType.Directional;
                light.intensity = 0.85f;
                light.color = new Color(0.86f, 0.88f, 1f);
            }

            RenderSettings.fog = true;
            RenderSettings.fogMode = FogMode.Linear;
            RenderSettings.fogColor = new Color(0.05f, 0.055f, 0.08f);
            RenderSettings.fogStartDistance = 22f;
            RenderSettings.fogEndDistance = ArenaHalfExtent * 1.6f;
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
            RenderSettings.ambientLight = new Color(0.16f, 0.17f, 0.22f);
        }

        private static Light FindLight()
        {
            return Object.FindFirstObjectByType<Light>();
        }

        private void CreateBlock(Transform parent, string blockName, Vector3 localPosition, Vector3 size)
        {
            GameObject block = GameObject.CreatePrimitive(PrimitiveType.Cube);
            block.name = blockName;
            block.transform.SetParent(parent, false);
            block.transform.localPosition = localPosition;
            block.transform.localScale = size;
            ApplyMaterial(block, new Color(0.18f, 0.18f, 0.21f));
        }

        private static void ApplyMaterial(GameObject target, Color tint)
        {
            Renderer renderer = target.GetComponent<Renderer>();
            if (renderer != null)
            {
                renderer.sharedMaterial = CreateMaterial(tint);
            }
        }

        private static Shader _litShader;

        /// <summary>
        /// Finds a lit shader, preferring URP's because that is the pipeline this
        /// project targets, with fallbacks so a missing pipeline does not produce
        /// magenta geometry.
        /// </summary>
        private static Shader ResolveLitShader()
        {
            if (_litShader != null)
            {
                return _litShader;
            }

            _litShader = Shader.Find("Universal Render Pipeline/Lit");

            if (_litShader == null)
            {
                _litShader = Shader.Find("Standard");
            }

            if (_litShader == null)
            {
                _litShader = Shader.Find("Sprites/Default");
            }

            return _litShader;
        }

        public static Material CreateMaterial(Color tint)
        {
            Shader shader = ResolveLitShader();

            if (shader == null)
            {
                return null;
            }

            var material = new Material(shader) { name = "Runtime " + ColorUtility.ToHtmlStringRGB(tint) };

            // URP's Lit shader uses _BaseColor. Built-in and sprite shaders use
            // _Color. Setting whichever exists avoids a silently white material.
            if (material.HasProperty("_BaseColor"))
            {
                material.SetColor("_BaseColor", tint);
            }

            if (material.HasProperty("_Color"))
            {
                material.SetColor("_Color", tint);
            }

            if (material.HasProperty("_Smoothness"))
            {
                material.SetFloat("_Smoothness", 0.12f);
            }

            if (material.HasProperty("_Metallic"))
            {
                material.SetFloat("_Metallic", 0f);
            }

            return material;
        }

        private void BuildHud()
        {
            if (!BuildHud)
            {
                return;
            }

            Hud = HudController.Create(transform, InputDriver, Session);
        }

        private void Update()
        {
            if (!_started || Session == null)
            {
                return;
            }

            float deltaTime = Time.deltaTime;

            // Input is gathered in one place, before the simulation runs, so every
            // fixed step in this frame sees a consistent set of intent. The HUD goes
            // first: on-screen controls write into the driver, and the driver is then
            // polled once, covering touch and keyboard alike.
            if (Hud != null)
            {
                Hud.PollInput();
            }

            InputDriver.CameraTransform = CameraRig != null ? CameraRig.transform : null;
            InputDriver.Poll();

            Session.Update(deltaTime);

            SyncViews(deltaTime);
            ExpireDeadViews(deltaTime);

            if (Hud != null)
            {
                Hud.Refresh();
            }

            TickAutoSave(deltaTime);
        }

        private void SyncViews(float deltaTime)
        {
            for (int i = 0; i < _views.Count; i++)
            {
                _views[i].Sync(deltaTime);
            }
        }

        private void ExpireDeadViews(float deltaTime)
        {
            for (int i = _deadViews.Count - 1; i >= 0; i--)
            {
                _deadViewTimers[i] -= deltaTime;

                if (_deadViewTimers[i] > 0f)
                {
                    continue;
                }

                CombatantView view = _deadViews[i];
                _deadViews.RemoveAt(i);
                _deadViewTimers.RemoveAt(i);
                _views.Remove(view);

                if (view.Combatant != null)
                {
                    _viewsById.Remove(view.Combatant.Id);
                }

                if (view.gameObject != null)
                {
                    Destroy(view.gameObject);
                }
            }
        }

        private void TickAutoSave(float deltaTime)
        {
            if (!AutoSave || AutoSaveIntervalSeconds <= 0f)
            {
                return;
            }

            _autoSaveTimer += deltaTime;

            if (_autoSaveTimer < AutoSaveIntervalSeconds)
            {
                return;
            }

            _autoSaveTimer = 0f;
            TrySave();
        }

        /// <summary>Writes the current session to its slot. Returns false with a message on failure.</summary>
        public bool TrySave(out string error)
        {
            error = null;

            if (Session == null || SaveManager == null)
            {
                error = "There is no session to save.";
                return false;
            }

            Session.SlotId = SaveSlot;

            SaveGame save = Session.CreateSave();
            SaveResult result = SaveManager.Save(save);

            if (!result.Success)
            {
                error = result.Error;
                Debug.LogWarning("Save failed: " + result.Error);
                return false;
            }

            return true;
        }

        public bool TrySave()
        {
            return TrySave(out _);
        }

        /// <summary>Loads the slot into the running session.</summary>
        public bool TryLoad(out string error)
        {
            error = null;

            if (Session == null || SaveManager == null)
            {
                error = "There is no session to load into.";
                return false;
            }

            SaveResult result = SaveManager.Load(SaveSlot, out SaveGame save);

            if (!result.Success)
            {
                error = result.Error;
                return false;
            }

            Session.ApplySave(save);

            // The player's body must follow the restored position.
            _viewsById.TryGetValue(Session.Player.Id, out CombatantView playerView);
            if (playerView != null)
            {
                playerView.Sync(0f);
                CameraRig.SetTarget(playerView.transform, Session.Player);
            }

            return true;
        }

        public bool TryLoad()
        {
            return TryLoad(out _);
        }

        /// <summary>Restarts the encounter without reloading the scene.</summary>
        public void ResetEncounter()
        {
            if (Session == null)
            {
                return;
            }

            Session.Encounter.Reset();

            for (int i = 0; i < _views.Count; i++)
            {
                _views[i].ClearFeedback();
            }
        }
    }
}
